- name: set dns_prefix for dydx RPC
  set_fact:
    rpc: '{{ chain }}-dao-rpc-{{ number }}'
    api: '{{ chain }}-dao-api-{{ number }}'
    grpc: '{{ chain }}-dao-grpc-{{ number }}'
  when: type == 'relayer'

- name: set dns_prefix for dydx archive
  set_fact:
    rpc: '{{ chain }}-dao-archive-rpc-{{ number }}'
    api: '{{ chain }}-dao-archive-api-{{ number }}'
    grpc: '{{ chain }}-dao-archive-grpc-{{ number }}'
  when: type == 'archive'
