- name: Stop node process
  become: true
  systemd:
    name: '{{ cosmovisor_service_name }}'
    state: stopped
    enabled: false
  ignore_errors: true

- name: Remove project git folder
  file:
    path: '{{ user_dir }}/{{ folder }}'
    state: absent

- name: Remove node data folder
  file:
    path: '{{ user_dir }}/{{ folder }}'
    state: absent

- name: remove systemd file
  become: true
  file:
    path: '/etc/systemd/system/{{ cosmovisor_service_name }}.service'
    state: absent

- name: remove binary from go bin
  file:
    path: '{{ user_dir }}/{{ daemon }}'
    state: absent

- name: remove genesis file, snapshot file, state sync file and resync files
  file:
    path: '{{ item }}'
    state: absent
  loop:
  - '{{ user_dir }}/snapshot/{{ chain }}.sh'
  - '{{ user_dir }}/genesis/{{ chain }}.sh'
  - '{{ user_dir }}/state_sync/{{ chain }}.sh'
  - '{{ user_dir }}/state_sync/resync/{{ chain }}_recover.sh'
  - '{{ user_dir }}/state_sync/resync/{{ chain }}_resync.sh'

- name: remove nginx files
  become: true
  file:
    path: '{{ item }}'
    state: absent
  loop:
  - '/etc/nginx/sites-enabled/{{ chain }}-api'
  - '/etc/nginx/sites-enabled/{{ chain }}-rpc'

- name: remove snapshot cronjob
  cron:
    user: '{{ ansible_user }}'
    name: '{{ chain }} snapshot'
    state: absent

- name: remove resync cronjob
  cron:
    user: '{{ ansible_user }}'
    name: '{{ chain }} resync'
    state: absent
