- name: Main
  hosts: "{{ target }}"
  gather_facts: false
  vars_files:
    - "{{ var_file }}"
  roles:
    - node_install
    - node_initialize
    - node_configure
    - node_launch
    - role: support_sync_snapshot
      when: snapshot_url is defined
    - role: support_prometheus
      when: prometheus is defined and prometheus | bool
- name: Setup Prometheus Monitoring on Chain
  hosts: telemetry
  gather_facts: true
  vars_files:
    - "{{ var_file }}"
  roles:
    - support_prometheus
  become: true