---
- name: Setup
  hosts: '{{ target }}'
  become: true
  gather_facts: true
  roles:
    - setup

- name: Setup Prometheus Node Monitoring
  hosts: telemetry
  gather_facts: false
  become: true
  tasks:
    - name: Write new entry to prom-node.yml
      blockinfile:
        path: "/etc/prometheus/prom-node.yml"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostvars[item].server_hostname }}"
        backup: true
        block: |
          - targets: ['{{ hostvars[item].ansible_host }}:9100']
            labels:
              instance: {{ hostvars[item].server_hostname }}
      loop: "{{ lookup('inventory_hostnames', target, wantlist=True) }}"
  tags:
    - monitoring