- name: Update minimum gas price on config file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/app.toml'
    regexp: '^minimum-gas-prices ='
    line: 'minimum-gas-prices = "{{ minimum_gas_price }}"'
    state: present
  when: minimum_gas_price is defined

- name: Restart cosmovisor service
  become: true
  systemd:
    name: '{{ cosmovisor_service_name }}'
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Pause for 10 seconds
  pause:
    seconds: 10

- name: Ensure it is running
  uri:
    url: 'http://localhost:{{ custom_port_prefix }}61'
    method: GET
    status_code: 200
  ignore_errors: true
