watcher_prom_file: "prom-watcher"
image: ghcr.io/kilnfi/cosmos-validator-watcher:latest
watcher_mainnet_port: 37
watcher_testnet_port: 38
watcher_port: "{{ watcher_mainnet_port if network == 'mainnet' else watcher_testnet_port }}"