- name: Set Cosmos Watcher prefix port
  var:
    watcher_port: "{{ watcher_mainnet_port if network == 'mainnet' else watcher_testnet_port }}"

- name: Write new entry to docker-compose.yml
  blockinfile:
    path: "/home/{{ ansible_user }}/cosmos-watcher-test/docker-compose.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ chain_id }}"
    backup: true
    block: |
        {{ chain }}-{{ network }}:
        image: {{ image }}
        restart: on-failure:5 # Restarts up to 5 times on failure
        command: >
          --http-addr :{{ watcher_port }}{{ custom_port_prefix }}
          --node {{ rpc_1 }}
          --node {{ rpc_2 }}
          --validator {{ validator_hex }}:"cs-{{ chain }}"
        ports:
          - "{{ watcher_port }}{{ custom_port_prefix }}:{{ watcher_port }}{{ custom_port_prefix }}"

- name: Update docker services
  shell:
    cmd: docker compose up -d
    chdir: /home/{{ ansible_user }}/cosmos-watcher-test

- name: Write new entry to prom-watcher.yml
  blockinfile:
    path: "/etc/prometheus/{{ watcher_prom_file }}-test.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ chain_id }}"
    backup: true
    block: |
      # {{ chain | upper }}
      - targets: ['{{ localhost }}:{{ watcher_port }}{{ custom_port_prefix }}']
        labels:
          chain: {{ chain }}
          chain_id: {{ chain_id }}
          network: {{ network }}
  loop: "{{ groups[target] }}"
  when: groups[target] is defined